import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import TransitionCurve from '@/components/TransitionCurve'
import TransitionStairs from '@/components/TransitionStairs'
import TransitionInner from '@/components/TransitionInner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header className="fixed z-[12] top-0 left-0 w-screen h-8">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
        </header> */}
        {/* <TransitionCurve>{children}</TransitionCurve> */}
        {/* <TransitionStairs>{ children }</TransitionStairs> */}
        <TransitionInner>{children}</TransitionInner>
      </body>
    </html>
  )
}
